FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/backend/package*.json ./packages/backend/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci -w packages/backend

COPY ./packages/backend ./packages/backend
COPY ./packages/shared ./packages/shared

ENV JWT_SECRET=asdoiuhgafnblkjshfd

RUN npm run build -w packages/backend

EXPOSE 8800

CMD [ "node", "packages/initdb.js"]

CMD [ "node", "packages/backend/dist/app.js" ]