version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URL=mongodb://db:27017/webshop

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        APP_API: http://localhost:4000
    ports:
      - "3000:3000"

  db:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /data/db